### ISSUE TITLE
generator.sample errors

### ISSUE THREAD

**Issue by martmists** [SunDwarf/gyukutai#3]
```python
>>> my_generator = (x for x in range(1000))
>>> my_generator.sample
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Program_Files\python_3.6\lib\site-packages\gyukutai\__init__.py", line 109, in _sample
    return random.choice(self)
  File "D:\Program_Files\python_3.6\lib\random.py", line 255, in choice
    i = self._randbelow(len(seq))
TypeError: object of type 'generator' has no len()
```

**Comment by SunDwarf** [comment]
cast it to a list

**Comment by martmists** [comment]
Doesn't that defeat the purpose of a generator?

**Comment by SunDwarf** [comment]
you can't pick a random item from a generator as it's not a sequence
